name: Update quotes.json

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # <-- required to push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: python update_quotes.py
      - name: Commit quotes.json
        run: |
          git config user.name "quotes-bot"
          git config user.email "actions@github.com"
          git add quotes.json
          git commit -m "update quotes" || exit 0
          git push
